In [ ]:
Survey_Data['id'] = list(map(str , Survey_Data['id']))
Score.set_index('id' , inplace = True)
Survey_Data['id'] = list(map(str , Survey_Data['id']))
Posture_Data['id'] = list(map(str , Posture_Data['id']))
Score['id'] = list(map(str , Score['id']))
Score_True= Score.loc[Survey_Data.loc[Survey_Data['효과'] == True]['id']]
Score_False = Score.loc[Survey_Data.loc[Survey_Data['효과'] == False]['id']]
G = np.array(Score_True['Good_Score'])
B = np.array(Score_False['Good_Score'])
F_statistic, pVal = stats.f_oneway(G,B )

In [ ]:
groupby_id = Posture_Data.groupby(['id', '이름'])


In [ ]:
Col_len = len(Score_True_Average.columns)
for c in range (Col_len):
    Score_True_Average.iloc[:,c ]

In [ ]:
plt.plot( Score_False_Average['VR'] , 'o', color='red')
plt.plot( Score_True_Average['VR'] , 'o', color='Blue')
plt.show()

In [ ]:
print( '데이터의 일원분산분석 결과 : F={0:.1f}, p={1:.5f}'.format(F_statistic, pVal))
if pVal < 0.05:
    print('P-value 값이 충분히 작음으로 인해 그룹의 평균값이 통계적으로 유의미하게 차이납니다.')

In [ ]:
diff = stats.ttest_ind(Score_True['Good_Score'],Score_False['Good_Score'])
print("T 검정통계량 = %.3f   P value = %.3f"%(diff))

In [ ]:
Score_Average = Score_True.append(Score_False)

In [ ]:
pd.get_dummies
Score_Average.drop ( ['Good_Score', 'Bad_Score'] , axis = 1 , inplace = True)

In [ ]:
log_clf = LogisticRegression(C=1) 
log_clf.fit(X,Y) 
log_clf.score(X, Y)

In [ ]:
x= rand.randint ( 0.10 ( 4,6 ))

In [ ]:
import matplotlib.pyplot as plt

import mglearn 
from sklearn.datasets import make_blobs


# 데이터 셋 가져오기

X,y = make_blobs(centers=4,random_state=8)

# 4개의 클래스를 2개로 

#y=y%2



# 2차원 데이터의 산점도 그리기

mglearn.discrete_scatter(X[:,0],X[:,1],y)



plt.xlabel("attr 1")

plt.ylabel("attr 2")

plt.legend()



plt.show()


In [ ]:
import matplotlib.pyplot as plt

import mglearn

from sklearn.svm import LinearSVC
from sklearn.datasets import make_blobs





# 데이터 셋 가져오기

X,y = make_blobs(centers=4,random_state=8)

# 4개의 클래스를 2개로 

y=y%2



# Linaer SVC분류기로 훈련해보기

linear_svm = LinearSVC().fit(X, y)



mglearn.plots.plot_2d_separator(linear_svm,X)
mglearn.discrete_scatter(X[:,0],X[:,1],y)

plt.xlabel("attr 0")

plt.ylabel("attr 1")

plt.show()



In [ ]:
import matplotlib.pyplot as plt

import mglearn

from sklearn.svm import LinearSVC

from sklearn.datasets import make_blobs

import numpy as np



# 데이터 셋 가져오기

X, y = make_blobs(centers=4, random_state=8)

# 4개의 클래스를 2개로 

y = y % 2



# 두 번쨰 특성을 제곱하여 추가

X_new = np.hstack([X, X[:, 1:] ** 2])


from mpl_toolkits.mplot3d import Axes3D, axes3d

figure = plt.figure()

# 3차원 그래프

ax = Axes3D(figure, elev=-152, azim=-26)



# y==0인 포인트를 먼저 그리고 그다음 y==1인포인트를 그린다.

mask = y == 0

ax.scatter(X_new[mask, 0], X_new[mask, 1], X_new[mask, 2], c='b', cmap=mglearn.cm2, s=60, edgecolor='k')

ax.scatter(X_new[~mask, 0], X_new[~mask, 1], X_new[~mask, 2], c='b', cmap=mglearn.cm2, marker="^", s=60, edgecolor='k')

ax.set_xlabel("attr 0")

ax.set_ylabel("attr 1")

ax.set_zlabel("attr 1^2")

plt.show()


In [ ]:
#file =  openpyxl.load_workbook('sample.xlsx')

# List Comprehension

In [ ]:
colors = ["red", "blue", "green", "yellow"]
result = "".join(colors)


In [3]:
example = 'python,jquery,javascript'

a, b, c = example.split(",")

In [ ]:
result = [i for i in range(10) if i % 2 == 0]
print(result)
result = [i+j for i in word_1 for j in word_2]

In [ ]:
words = 'The quick brown fox jumps over the lazy dog'.split()
print(words)

stuff = [[w.upper(), w.lower(), len(w)] for w in words]

for i in stuff:
    print(i)

In [7]:
{ i:j for  i,j in enumerate  ( 'One of the special concepts in Python is the idea of writing idiomatic code that is most aligned with the language features and ideals. In Python, we call this idiomatic code Pythonic. While this idea is easy to understand, it turns out to be fairly hard to make concrete'.split())}

{0: 'One',
 1: 'of',
 2: 'the',
 3: 'special',
 4: 'concepts',
 5: 'in',
 6: 'Python',
 7: 'is',
 8: 'the',
 9: 'idea',
 10: 'of',
 11: 'writing',
 12: 'idiomatic',
 13: 'code',
 14: 'that',
 15: 'is',
 16: 'most',
 17: 'aligned',
 18: 'with',
 19: 'the',
 20: 'language',
 21: 'features',
 22: 'and',
 23: 'ideals.',
 24: 'In',
 25: 'Python,',
 26: 'we',
 27: 'call',
 28: 'this',
 29: 'idiomatic',
 30: 'code',
 31: 'Pythonic.',
 32: 'While',
 33: 'this',
 34: 'idea',
 35: 'is',
 36: 'easy',
 37: 'to',
 38: 'understand,',
 39: 'it',
 40: 'turns',
 41: 'out',
 42: 'to',
 43: 'be',
 44: 'fairly',
 45: 'hard',
 46: 'to',
 47: 'make',
 48: 'concrete'}

In [8]:
alist = ['a1', 'a2', 'a3']
blist = ['b1', 'b2', 'b3']

for i, (a, b) in enumerate(zip(alist, blist)):
    print(i, a, b)

0 a1 b1
1 a2 b2
2 a3 b3


In [13]:
ex = [1,2,3,4,5]
list(map(    
    lambda x: x ** 2 if x % 2 == 0 else x,
    ex))

[1, 4, 3, 16, 5]

In [ ]:
# Reduce
from functools import reduce
print(reduce(lambda x, y: x+y, [1, 2, 3, 4, 5]))


In [15]:
a, b, c = ([1, 2], [3, 4], [5, 6])
print(a, b, c)

data = ([1, 2], [3, 4], [5, 6])
print(*data)

[1, 2] [3, 4] [5, 6]


In [1]:
import numpy as np

In [9]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
test =np.array(test_matrix).reshape(8,1)
test.dtype

dtype('int32')

In [8]:
type(test.reshape(-1, 1))

numpy.ndarray

In [20]:
test_example = np.array([[1, 2, 3], [4.5, 5, 6]], int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
a = np.array([[1, 2, 3]])
b = np.array([[2, 3, 4]])
np.concatenate( (a.T,b.T) ,axis=1)



array([[1, 2],
       [2, 3],
       [3, 4]])

In [36]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np.concatenate( (a,b.T) ,axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [23]:
np.arange(0,15,0.5).reshape(5,6)

array([[ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ,  7.5,  8. ,  8.5],
       [ 9. ,  9.5, 10. , 10.5, 11. , 11.5],
       [12. , 12.5, 13. , 13.5, 14. , 14.5]])

In [44]:
b = np.array([[5, 6]])
b.shape

(1, 2)

In [ ]:
np.where(a > 0, 3, 2)   # 0 보다 그면 3 작으면 2를 반환 
np.where( a>0 )  # 인덱스 값을 반환한다.

In [54]:
A = np.array([
[12, 13, 14, 12, 16, 14, 11, 10,  9],
[11, 14, 12, 15, 15, 16, 10, 12, 11],
[10, 12, 12, 15, 14, 16, 10, 12, 12],
[ 9, 11, 16, 15, 14, 16, 15, 12, 10],
[12, 11, 16, 14, 10, 12, 16, 12, 13],
[10, 15, 16, 14, 14, 14, 16, 15, 12],
[13, 17, 14, 10, 14, 11, 14, 15, 10],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 17, 19, 16, 17, 18, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 12, 14, 11, 12, 14, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11]])
B = A < 15

B.astype(np.int)

array([[1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 1, 1],
       [1, 1, 0, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 1],
       [1, 0, 0, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1]])

In [65]:
from pandas import Series, DataFrame
import pandas as pd
raw_data = {'first_name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'],
        'last_name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze'],
        'age': [42, 52, 36, 24, 73],
        'city': ['San Francisco', 'Baltimore', 'Miami', 'Douglas', 'Boston']}


df = DataFrame(raw_data, columns = ["first_name","last_name","age", "city", "debt"])
df

first_name last_name  age           city debt
0      Jason    Miller   42  San Francisco  NaN
1      Molly  Jacobson   52      Baltimore  NaN
2       Tina       Ali   36          Miami  NaN
3       Jake    Milner   24        Douglas  NaN
4        Amy     Cooze   73         Boston  NaN

In [60]:
df.debt= df.debt.astype(np.int)

In [66]:
df.debt = (df.age > 40).astype(np.int )

In [73]:
df.city

0    San Francisco
1        Baltimore
2            Miami
3          Douglas
4           Boston
Name: city, dtype: object

In [ ]:
grouped = df.groupby("Team")
score = lambda x: (x - x.mean()) / x.std()
grouped.transform(score)

In [ ]:
df_phone.groupby(['month', 'item']).agg({'duration':sum,      # find the sum of the durations for each group
                                     'network_type': "count", # find the number of network type entries
                                     'date': 'first'})    # get the first date per group